-- TABLA DE PEDIDOS (ORDERS)
-- Guarda la información vital de la transacción
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  buyer_id uuid references auth.users not null, -- Quién compró
  total numeric not null,                       -- Monto total $
  status text default 'processing',             -- pending, processing, shipped, delivered, cancelled
  items jsonb not null,                         -- Guardamos el snapshot de los productos (precio al momento de compra, cantidad, id, vendedor)
  shipping_address jsonb not null               -- Dirección de envío snapshot
);

-- Políticas de Seguridad (RLS)
alter table public.orders enable row level security;

-- 1. El comprador puede ver sus propios pedidos
create policy "Compradores ven sus pedidos"
on public.orders for select
using ( auth.uid() = buyer_id );

-- 2. El comprador puede crear pedidos
create policy "Compradores crean pedidos"
on public.orders for insert
with check ( auth.uid() = buyer_id );

-- 3. (Opcional) Los vendedores deberían poder ver pedidos donde ELLOS son vendedores.
-- Como 'items' es un JSONB array, esto requiere una consulta avanzada, 
-- pero para el MVP permitiremos que la API filtre por vendedor en el código 
-- o crearemos una función RPC (Remote Procedure Call) más adelante.
